#pragma once
#include <Arduino.h>
const String protocolMapJson = R"data(
{
    "SPEED": "9O",
    "P_SPEED": "9P",
    "ANGLE": "9A",
    "ANGLE_SET": "9S",
    "FAN": "9F",
    "MOVE_FORWARD": "M1",
    "MOVE_BACKWARD": "M2",
    "TURN_LEFT": "T1",
    "TURN_RIGHT": "T2",
    "STOP": "S0",
    "SHOOT": "S1",
    "REFILL": "R1",
    "LOCK_TARGET": "L1",
    "ROTATE_MAG_L": "0Q",
    "ROTATE_MAG_R": "0W",
    "LASER": "9L",
    "LED": "9E",
    "FAN_AUTO": "9H",
    "battery": "B1",
    "temp": "T0",
    "speed": "S2",
    "signal": "W1",
    "ping": "P0",
    "fan": "F1",
    "core0": "C0",
    "core1": "C1",
    "mota": "MA",
    "motb": "MB",
    "roll": "R0",
    "pitch": "P1",
    "yaw": "Y0",
    "ball": "I1",
    "mag": "I2",
    "ready": "I3",
    "locked": "I4",
    "line": "L0",
    "us": "U0"
}
)data";